from __future__ import annotations

import os
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent

LVGL_VERSIONS = {"v8", "v9"}

IMAGE_FORMATS = {"c_array", "binary", "both"}

COLOR_FORMATS = {"RGB565"}

DEFAULT_FONT_CANDIDATES = [
    Path(os.environ.get("LVGL_PLACEHOLDER_TTF", "")),
    Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts" / "simhei.ttf",
    Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts" / "msyh.ttc",
    Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts" / "simsun.ttc",
    Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts" / "arial.ttf",
]

ASSET_INPUT_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".ppm", ".pnm"}

INITIAL_LOADING_DESIGN_FILE = "initial_loading.png"

INITIAL_LOADING_BACKGROUND_FILE = "background1.jpg"

INITIAL_LOADING_PET_FILE = "pet.png"

DISPLAY_CONFIG: dict[str, Any] = {
    "schema": "freertos-embedded-architect.lvgl.display-config.v1",
    "display": {
        "width": 480,
        "height": 800,
        "orientation": "portrait",
        "color_depth": 16,
        "color_format": "RGB565",
        "dpi": 160,
    },
    "lvgl": {"version": "v9", "image_widget": {"v8": "lv_img", "v9": "lv_image"}},
    "fonts": {
        "body": {"name": "ui_font_body_16", "size": 16, "languages": ["en", "zh"]},
        "title": {"name": "ui_font_title_24", "size": 24, "languages": ["en", "zh"]},
        "number": {"name": "ui_font_number_32", "size": 32, "languages": ["digits"]},
        "icon": {"name": "ui_font_icon_16", "size": 16, "languages": ["symbols"]},
    },
    "layout_policy": {
        "preferred": ["flex", "grid"],
        "forbidden_by_default": ["lv_obj_set_pos", "lv_obj_set_x", "lv_obj_set_y"],
        "exception_marker": "LVGL_LAYOUT_EXCEPTION",
        "absolute_position_exceptions": [
            "hardware overlay alignment",
            "pixel-level calibration",
            "short-lived animation staging",
        ],
    },
    "asset_policy": {
        "default_image_output": "c_array",
        "default_color_format": "RGB565",
        "binary_allowed": True,
        "runtime_path_images": "avoid unless decoder/cache lifecycle is proven",
    },
}

REGRESSION_SANDBOX_CONFIG: dict[str, Any] = {
    "schema": "freertos-embedded-architect.lvgl.regression-sandbox-config.v1",
    "template_path": "assets/lvgl_regression_sandbox_template",
    "default_width": 480,
    "default_height": 800,
    "default_frames": 120,
    "timeout_seconds": 20,
    "pixel_threshold": {"max_changed_ratio": 0.01, "max_channel_delta": 8},
    "log_error_patterns": [
        "LVGL ASSERT",
        "SDL2 libraries not found",
        "SDL initialization failed",
        "image decoder failed",
        "resource missing",
        "segmentation fault",
        "access violation",
    ],
    "excluded_template_paths": [".git", ".cache", "build", "bin", "*.obj", "*.log", "temp_*"],
    "default_cache_dir": "artifacts/lvgl_render_cache",
}

LVGL_TOOL_SCHEMAS: list[dict[str, Any]] = [
    {
        "name": "get_lvgl_theme_skill",
        "description": "Return Flex/Grid-first LVGL UI generation rules and default display config. Use before generating any LVGL page to load layout constraints (no absolute positioning, Flex/Grid preferred).",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "convert_image_to_lvgl_source",
        "description": "Convert a cut image (PNG/JPG/BMP) into LVGL RGB565 C-array header and/or binary asset. Returns generated file paths. Use when user provides design cut images for LVGL UI.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "input_path": {"type": "string"},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_assets"},
                "name": {"type": "string"},
                "format": {"type": "string", "enum": sorted(IMAGE_FORMATS), "default": "c_array"},
                "color_format": {"type": "string", "enum": sorted(COLOR_FORMATS), "default": "RGB565"},
                "lvgl_version": {"type": "string", "enum": sorted(LVGL_VERSIONS), "default": "v8"},
            },
            "required": ["input_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "generate_lvgl_layout_spec",
        "description": "Create Flex/Grid-first LVGL page spec JSON from design notes and asset list. Returns spec object for generate_lvgl_page_code. Use as step 1 of LVGL page generation pipeline.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "page_name": {"type": "string", "default": "page"},
                "design_notes": {"type": "string", "default": ""},
                "assets": {"type": "array", "items": {"type": "object"}},
                "display_config_uri": {"type": "string", "default": "lvgl://display-config"},
                "layout": {"type": "string", "enum": ["auto", "flex", "grid"], "default": "auto"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "generate_lvgl_page_code",
        "description": "Generate LVGL C/H page scaffold from a layout spec. Returns .c/.h file paths with Flex/Grid layout, event handlers, and state machine. Use as step 2 of LVGL page generation pipeline.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "spec_json": {"type": "object"},
                "spec_path": {"type": "string"},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_ui"},
                "lvgl_version": {"type": "string", "enum": sorted(LVGL_VERSIONS), "default": "v8"},
                "custom_events_enabled": {"type": "boolean", "default": True},
                "server_update_event_name": {"type": "string", "default": "auto"},
                "state_machine_enabled": {"type": "boolean", "default": True},
                "states": {"type": "array", "items": {"type": "string"}, "default": ["init", "loading", "ready", "error"]},
            },
            "additionalProperties": True,
        },
    },
    {
        "name": "generate_initial_loading_page",
        "description": "Generate the pixel-matched initial loading LVGL page from ui/initial_loading.png, background1.jpg, and pet.png.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "design_dir": {"type": "string", "default": "ui"},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_ui/initial_loading"},
                "page_name": {"type": "string", "default": "initial_loading"},
                "design_path": {"type": "string"},
                "background_path": {"type": "string"},
                "pet_path": {"type": "string"},
                "loading_path": {"type": "string", "description": "Optional loading reference template for bbox calibration; defaults to ui/loadiing2.png when present."},
                "loading_reference_path": {"type": "string", "description": "Alias for loading_path."},
                "background_src": {"type": "string", "default": "S:/ui/background1.jpg"},
                "pet_src": {"type": "string", "default": "S:/ui/pet.png"},
                "background_src_macro": {"type": "string", "default": "UI_IMG_SRC_INITIAL_LOADING_BG"},
                "pet_src_macro": {"type": "string", "default": "UI_IMG_SRC_INITIAL_LOADING_PET"},
                "auto_analyze": {"type": "boolean", "default": True},
                "return_mode": {"type": "string", "enum": ["compact", "full"], "default": "full", "description": "Full preserves the legacy manifest-shaped response; compact returns key bboxes and artifact paths."},
                "title_text": {"type": "string", "default": "Loading"},
                "body_text": {"type": "string", "default": "Please wait"},
                "title_text_macro": {"type": "string", "default": "UI_TEXT_INITIAL_LOADING_TITLE"},
                "body_text_macro": {"type": "string", "default": "UI_TEXT_INITIAL_LOADING_BODY"},
                "lvgl_version": {"type": "string", "enum": sorted(LVGL_VERSIONS), "default": "v9"},
                "custom_events_enabled": {"type": "boolean", "default": True},
                "server_update_event_name": {"type": "string", "default": "auto"},
                "state_machine_enabled": {"type": "boolean", "default": True},
                "states": {"type": "array", "items": {"type": "string"}, "default": ["init", "loading", "ready", "error"]},
                "width": {"type": "integer", "default": 480},
                "height": {"type": "integer", "default": 800},
                "pet_x": {"type": "integer", "default": 118},
                "pet_y": {"type": "integer", "default": 111},
                "pet_w": {"type": "integer", "default": 271},
                "pet_h": {"type": "integer", "default": 391},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "generate_interactive_scene_page",
        "description": "Generate the interactive scene LVGL page from a design screenshot and mood cut assets.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "design_dir": {"type": "string", "default": "ui"},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_ui/interactive_scene"},
                "page_name": {"type": "string", "default": "interactive_scene"},
                "design_path": {"type": "string"},
                "background_path": {"type": "string"},
                "pet_path": {"type": "string"},
                "normal_path": {"type": "string"},
                "happy_path": {"type": "string"},
                "sad_path": {"type": "string"},
                "angry_path": {"type": "string"},
                "mood_order": {"type": "array", "items": {"type": "string"}, "description": "Mood key order, e.g. ['calmness','good','down','stressed']."},
                "mood_keys": {"type": "array", "items": {"type": "string"}, "description": "Alias for mood_order."},
                "mood_paths": {"type": "object", "additionalProperties": {"type": "string"}, "description": "Map mood key to cutout image path."},
                "background_src": {"type": "string", "default": "S:/ui/background1.jpg"},
                "pet_src": {"type": "string", "default": "S:/ui/pet.png"},
                "normal_src": {"type": "string", "default": "S:/ui/mood_normal.png"},
                "happy_src": {"type": "string", "default": "S:/ui/mood_happy.png"},
                "sad_src": {"type": "string", "default": "S:/ui/mood_sad.png"},
                "angry_src": {"type": "string", "default": "S:/ui/mood_angry.png"},
                "mood_src": {"type": "object", "additionalProperties": {"type": "string"}, "description": "Map mood key to runtime LVGL image source expression or macro."},
                "background_src_macro": {"type": "string", "default": "UI_IMG_SRC_INTERACTIVE_BG"},
                "pet_src_macro": {"type": "string", "default": "UI_IMG_SRC_INTERACTIVE_PET"},
                "normal_src_macro": {"type": "string", "default": "UI_IMG_SRC_MOOD_NORMAL"},
                "happy_src_macro": {"type": "string", "default": "UI_IMG_SRC_MOOD_HAPPY"},
                "sad_src_macro": {"type": "string", "default": "UI_IMG_SRC_MOOD_SAD"},
                "angry_src_macro": {"type": "string", "default": "UI_IMG_SRC_MOOD_ANGRY"},
                "mood_src_macros": {"type": "object", "additionalProperties": {"type": "string"}, "description": "Map mood key to generated page source macro."},
                "asset_header": {"type": "string", "description": "Optional header included by generated page C before image source macro defaults."},
                "top_text": {"type": "string", "default": "I am completely\nforgiven-past,\npresent, and"},
                "title_text": {"type": "string", "default": "How's your mood"},
                "hint_text": {"type": "string", "default": "today?"},
                "top_text_macro": {"type": "string", "default": "UI_TEXT_INTERACTIVE_SCENE_TOP"},
                "title_text_macro": {"type": "string", "default": "UI_TEXT_INTERACTIVE_SCENE_TITLE"},
                "hint_text_macro": {"type": "string", "default": "UI_TEXT_INTERACTIVE_SCENE_HINT"},
                "auto_analyze": {"type": "boolean", "default": True},
                "return_mode": {"type": "string", "enum": ["compact", "full"], "default": "full", "description": "Full preserves the legacy manifest-shaped response; compact returns key bboxes and artifact paths."},
                "preview_design_reference": {"type": "boolean", "default": False, "description": "Force the design screenshot as preview.html base with transparent interactive hotspots. When false, the background consistency gate can still auto-switch to design-reference mode."},
                "background_gate_threshold": {"type": "number", "default": 24.0, "description": "Average RGB absolute-delta threshold for blocking layered pixel reconstruction when the clean background differs from the design screenshot."},
                "lvgl_version": {"type": "string", "enum": sorted(LVGL_VERSIONS), "default": "v9"},
                "custom_events_enabled": {"type": "boolean", "default": True},
                "server_update_event_name": {"type": "string", "default": "auto"},
                "state_machine_enabled": {"type": "boolean", "default": True},
                "states": {"type": "array", "items": {"type": "string"}, "default": ["idle", "interacting", "selected", "error"]},
                "width": {"type": "integer", "default": 480},
                "height": {"type": "integer", "default": 800},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "analyze_layout_and_patch",
        "description": "Compare a visual-model JSON tree with existing LVGL C code and produce an incremental patch instead of regenerating the file.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layout_json": {"type": "object"},
                "layout_path": {"type": "string"},
                "target_path": {"type": "string"},
                "existing_code": {"type": "string"},
                "patch_path": {"type": "string"},
                "apply": {"type": "boolean", "default": False},
                "parent_var": {"type": "string", "default": "root"},
                "lvgl_version": {"type": "string", "enum": sorted(LVGL_VERSIONS), "default": "v9"},
                "exception_reason": {"type": "string", "default": "visual model incremental layout patch"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "convert_assets_to_lvgl",
        "description": "Batch-convert PNG/JPG/BMP/PPM cut assets to LVGL image descriptors and emit ui_assets registry files.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "input_paths": {"type": "array", "items": {"type": "string"}},
                "source_dir": {"type": "string"},
                "recursive": {"type": "boolean", "default": True},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_assets"},
                "project_config": {"type": "object"},
                "converter_preset": {"type": "string", "enum": ["lv_img_conv", "lvgl_image_converter"], "description": "Preset converter name (server-side allowlist). Leave empty for built-in RGB565 converter."},
                "strict_converter": {"type": "boolean", "default": False},
                "asset_prefix": {"type": "string", "default": "ui_img"},
                "format": {"type": "string", "enum": sorted(IMAGE_FORMATS), "default": "c_array"},
                "color_format": {"type": "string", "default": "RGB565"},
                "lvgl_version": {"type": "string", "enum": sorted(LVGL_VERSIONS), "default": "v9"},
                "timeout_seconds": {"type": "integer", "default": 120},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "generate_font_glyph",
        "description": "Extract glyphs from layout/text and run local lv_font_conv to generate a compact LVGL font plus placeholder macro header.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layout_json": {"type": "object"},
                "layout_path": {"type": "string"},
                "text": {"type": "string"},
                "text_path": {"type": "string"},
                "fallback_text": {"type": "string"},
                "font_path": {"type": "string"},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_fonts"},
                "font_name": {"type": "string"},
                "size": {"type": "integer", "default": 16},
                "bpp": {"type": "integer", "default": 4},
                "extra_args": {"type": "array", "items": {"type": "string"}},
                "timeout_seconds": {"type": "integer", "default": 120},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "validate_lvgl_layout_code",
        "description": "Statically check LVGL code for forbidden absolute layout and asset path drift.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "prepare_lvgl_sim_project",
        "description": "Create a lightweight LVGL simulator skeleton and report local LVGL/SDL readiness.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "output_dir": {"type": "string", "default": "artifacts/lvgl_sim"},
                "lvgl_root": {"type": "string"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "prepare_lvgl_regression_sandbox",
        "description": "Copy the LVGL UI rendering/regression sandbox template into an isolated work directory.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "output_dir": {"type": "string", "default": "artifacts/lvgl_regression_sandbox"},
                "width": {"type": "integer", "default": 480},
                "height": {"type": "integer", "default": 800},
                "lvgl_root": {"type": "string"},
                "sdl2_root": {"type": "string"},
                "sdl2_dir": {"type": "string"},
                "sdl2_bin": {"type": "string"},
                "ui_under_test_dir": {"type": "string"},
                "ui_entry_function": {"type": "string"},
                "ui_header": {"type": "string"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "build_lvgl_regression_sandbox",
        "description": "Configure and build a prepared LVGL regression sandbox with CMake.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "sandbox_dir": {"type": "string"},
                "build_dir": {"type": "string"},
                "lvgl_root": {"type": "string"},
                "sdl2_root": {"type": "string"},
                "sdl2_dir": {"type": "string"},
                "sdl2_bin": {"type": "string"},
                "ui_under_test_dir": {"type": "string"},
                "generator": {"type": "string"},
                "toolchain_bin": {"type": "string"},
                "ninja_bin": {"type": "string"},
                "c_compiler": {"type": "string"},
                "cxx_compiler": {"type": "string"},
                "build_type": {"type": "string", "default": "Debug"},
                "timeout_seconds": {"type": "integer", "default": 120},
                "parallel": {"type": "integer", "default": 4},
            },
            "required": ["sandbox_dir"],
            "additionalProperties": False,
        },
    },
    {
        "name": "run_lvgl_regression_sandbox",
        "description": "Run a built LVGL regression sandbox executable and scan runtime logs.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "sandbox_dir": {"type": "string"},
                "build_dir": {"type": "string"},
                "executable": {"type": "string"},
                "output_dir": {"type": "string"},
                "sdl2_dir": {"type": "string"},
                "sdl2_bin": {"type": "string"},
                "toolchain_bin": {"type": "string"},
                "timeout_seconds": {"type": "integer", "default": 20},
            },
            "required": ["sandbox_dir"],
            "additionalProperties": False,
        },
    },
    {
        "name": "compare_lvgl_screenshot",
        "description": "Compare actual and baseline LVGL screenshots using pixel thresholds.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "actual_path": {"type": "string"},
                "baseline_path": {"type": "string"},
                "max_changed_ratio": {"type": "number", "default": 0.01},
                "max_channel_delta": {"type": "integer", "default": 8},
            },
            "required": ["actual_path", "baseline_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "compare_lvgl_object_tree",
        "description": "Compare actual and baseline LVGL object-tree JSON by node count, widget types, and label text.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "actual_path": {"type": "string"},
                "baseline_path": {"type": "string"},
            },
            "required": ["actual_path", "baseline_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "lvgl_render",
        "description": "Render one LVGL C snippet or UI entry through the local sandbox, or use pure-Python preview mode, and return PNG screenshot plus object-tree JSON.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "c_code": {"type": "string"},
                "c_header": {"type": "string"},
                "output_dir": {"type": "string", "default": "artifacts/lvgl_render"},
                "render_mode": {"type": "string", "enum": ["auto", "probe", "preview"], "default": "auto"},
                "spec_json": {"type": "object"},
                "spec_path": {"type": "string"},
                "object_tree_json": {"type": "object"},
                "object_tree_path": {"type": "string"},
                "base_dir": {"type": "string"},
                "page_name": {"type": "string", "default": "page"},
                "design_notes": {"type": "string"},
                "width": {"type": "integer", "default": 480},
                "height": {"type": "integer", "default": 800},
                "lvgl_root": {"type": "string"},
                "sdl2_root": {"type": "string"},
                "sdl2_dir": {"type": "string"},
                "sdl2_bin": {"type": "string"},
                "ui_under_test_dir": {"type": "string"},
                "ui_entry_function": {"type": "string", "default": "ui_snippet_create"},
                "ui_header": {"type": "string", "default": "ui_snippet.h"},
                "toolchain_bin": {"type": "string"},
                "ninja_bin": {"type": "string"},
                "c_compiler": {"type": "string"},
                "cxx_compiler": {"type": "string"},
                "generator": {"type": "string"},
                "build_dir": {"type": "string"},
                "timeout_seconds": {"type": "integer", "default": 120},
                "parallel": {"type": "integer", "default": 4},
                "cache_dir": {"type": "string", "default": "artifacts/lvgl_render_cache"},
                "snippet_dir": {"type": "string"},
            },
            "additionalProperties": True,
        },
    },
    {
        "name": "run_lvgl_ui_regression",
        "description": "Call lvgl_render, then compare screenshot pixels, optional object-tree JSON, and runtime log issues against baselines.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "output_dir": {"type": "string"},
                "baseline_path": {"type": "string"},
                "baseline_object_tree_path": {"type": "string"},
                "c_code": {"type": "string"},
                "render_mode": {"type": "string", "enum": ["auto", "probe", "preview"], "default": "auto"},
                "spec_json": {"type": "object"},
                "spec_path": {"type": "string"},
                "object_tree_json": {"type": "object"},
                "object_tree_path": {"type": "string"},
                "base_dir": {"type": "string"},
                "page_name": {"type": "string", "default": "page"},
                "design_notes": {"type": "string"},
                "width": {"type": "integer", "default": 480},
                "height": {"type": "integer", "default": 800},
                "lvgl_root": {"type": "string"},
                "sdl2_root": {"type": "string"},
                "sdl2_dir": {"type": "string"},
                "sdl2_bin": {"type": "string"},
                "ui_under_test_dir": {"type": "string"},
                "toolchain_bin": {"type": "string"},
                "ninja_bin": {"type": "string"},
                "c_compiler": {"type": "string"},
                "cxx_compiler": {"type": "string"},
                "timeout_seconds": {"type": "integer", "default": 120},
                "parallel": {"type": "integer", "default": 4},
                "cache_dir": {"type": "string", "default": "artifacts/lvgl_render_cache"},
                "snippet_dir": {"type": "string"},
            },
            "additionalProperties": True,
        },
    },
    {
        "name": "list_lvgl_regression_artifacts",
        "description": "List screenshots, logs, JSON files, and other regression artifacts in a sandbox.",
        "inputSchema": {
            "type": "object",
            "properties": {"sandbox_dir": {"type": "string"}},
            "required": ["sandbox_dir"],
            "additionalProperties": False,
        },
    },

]

__all__ = [
    "ASSET_INPUT_EXTENSIONS",
    "COLOR_FORMATS",
    "DEFAULT_FONT_CANDIDATES",
    "DISPLAY_CONFIG",
    "IMAGE_FORMATS",
    "INITIAL_LOADING_BACKGROUND_FILE",
    "INITIAL_LOADING_DESIGN_FILE",
    "INITIAL_LOADING_PET_FILE",
    "LVGL_TOOL_SCHEMAS",
    "LVGL_VERSIONS",
    "REGRESSION_SANDBOX_CONFIG",
    "ROOT",
]
