#!/usr/bin/env python3
"""Generate rule test coverage matrix.

Scans constraint_quick_index.md and checker_registry.py to produce
a coverage report showing which constraints have automated checkers
and test fixtures.

Output modes:
  --json   Machine-readable JSON
  --md     Markdown table (default)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIR = ROOT / "tools"
sys.path.insert(0, str(TOOLS_DIR))

from checker_registry import ALL_CHECKERS, SELF_TEST_CASES, VALIDATE_EXAMPLE_CASES


def configure_stdout() -> None:
    """Keep Markdown status glyphs usable from legacy Windows terminals."""
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except OSError:
                pass


def parse_constraints() -> list[dict]:
    """Parse constraint_quick_index.md to extract C1-C46 entries."""
    qi_path = ROOT / "references" / "constraint_quick_index.md"
    if not qi_path.is_file():
        return []

    text = qi_path.read_text(encoding="utf-8")
    constraints = []

    # Match table rows: | C1 | name | scenario | shard |
    # Also handle | OTA | ... | pattern
    pattern = re.compile(
        r"^\|\s*(C\d+|OTA)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(\w+)\s*\|",
        re.MULTILINE,
    )
    for m in pattern.finditer(text):
        cid = m.group(1)
        name = m.group(2).strip()
        scenario = m.group(3).strip()
        shard = m.group(4).strip()
        constraints.append({
            "id": cid,
            "name": name,
            "scenario": scenario,
            "shard": shard,
        })

    return constraints


def build_checker_map() -> dict[str, list[str]]:
    """Map constraint ID -> list of checker names."""
    result: dict[str, list[str]] = {}
    for spec in ALL_CHECKERS:
        for domain in spec.domains:
            keys = [domain]
            if "." in domain:
                keys.append(domain.split(".", 1)[0])
            for key in keys:
                checkers = result.setdefault(key, [])
                if spec.name not in checkers:
                    checkers.append(spec.name)
    return result


def build_fixture_map() -> dict[str, dict]:
    """Map script -> {self_test: [...], example: [...]}."""
    result: dict[str, dict] = {}
    for case in SELF_TEST_CASES:
        result.setdefault(case.script, {"self_test": [], "example": []})
        result[case.script]["self_test"].append(case.label)
    for case in VALIDATE_EXAMPLE_CASES:
        result.setdefault(case.script, {"self_test": [], "example": []})
        result[case.script]["example"].append(case.label)
    return result


def classify_coverage(
    constraint_id: str,
    checker_map: dict[str, list[str]],
    fixture_map: dict[str, dict],
) -> str:
    """Classify constraint coverage as covered/partial/manual/missing."""
    checkers = checker_map.get(constraint_id, [])
    if not checkers:
        return "missing"

    # Check if any checker has fixtures
    has_fixture = False
    has_example = False
    for checker_name in checkers:
        # Find the script for this checker
        spec = next((c for c in ALL_CHECKERS if c.name == checker_name), None)
        if spec and spec.script in fixture_map:
            fixtures = fixture_map[spec.script]
            if fixtures["self_test"]:
                has_fixture = True
            if fixtures["example"]:
                has_example = True

    if has_fixture and has_example:
        return "covered"
    elif has_fixture or has_example:
        return "partial"
    else:
        return "partial"  # checker exists but no fixtures


def main() -> int:
    configure_stdout()
    parser = argparse.ArgumentParser(description="Generate rule test coverage matrix")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    parser.add_argument("--md", action="store_true", help="Output Markdown (default)")
    parser.add_argument("--output", "-o", help="Write to file instead of stdout")
    args = parser.parse_args()

    constraints = parse_constraints()
    checker_map = build_checker_map()
    fixture_map = build_fixture_map()

    rows = []
    for c in constraints:
        cid = c["id"]
        checkers = checker_map.get(cid, [])
        coverage = classify_coverage(cid, checker_map, fixture_map)
        checker_names = ", ".join(checkers) if checkers else "-"
        rows.append({
            "id": cid,
            "name": c["name"],
            "shard": c["shard"],
            "checkers": checker_names,
            "coverage": coverage,
        })

    if args.json:
        output = json.dumps(rows, ensure_ascii=False, indent=2)
    else:
        lines = [
            "# Rule Test Coverage",
            "",
            "> Auto-generated by check_rule_coverage.py.",
            "> Coverage: covered = checker + self-test + example, partial = checker + some fixtures,",
            "> missing = no checker, manual = documented but requires human review.",
            "",
            "| Constraint | Name | Shard | Checker | Status |",
            "|---|---|---|---|---|",
        ]
        for r in rows:
            status_icon = {
                "covered": "✅",
                "partial": "⚠️",
                "missing": "❌",
                "manual": "📝",
            }.get(r["coverage"], "?")
            lines.append(
                f"| {r['id']} | {r['name']} | {r['shard']} | {r['checkers']} | {status_icon} {r['coverage']} |"
            )
        output = "\n".join(lines) + "\n"

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Written to {args.output}")
    else:
        print(output)

    # Summary
    counts = {}
    for r in rows:
        counts[r["coverage"]] = counts.get(r["coverage"], 0) + 1
    total = len(rows)
    print(f"\nSummary: {total} constraints", file=sys.stderr)
    for k in ["covered", "partial", "missing", "manual"]:
        if k in counts:
            print(f"  {k}: {counts[k]}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
